# Generated by Django 4.1.5 on 2023-03-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_advertisement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
